image: python:3.8
stages:
  - build
  - deploy
  # - s3Folder

build:
  stage: build
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  script:
    - sam build

deploy:
  stage: deploy
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  when: manual
  script:
    - sam deploy --template-file template.yaml --stack-name $CI_COMMIT_BRANCH-upschool-stack --region ap-south-1 --no-fail-on-empty-changeset --parameter-overrides ParameterKey=Stage,ParameterValue=$CI_COMMIT_BRANCH ParameterKey=Region,ParameterValue=ap-south-1 ParameterKey=Account,ParameterValue=036801103583
# s3Folder:
#   stage: s3Folder
#   before_script:
#     - pip3 install awscli --upgrade
#     - pip3 install aws-sam-cli --upgrade
#   when: manual
#   script:
#     - aws s3api put-object --bucket $CI_COMMIT_BRANCH-facto --key uploads
#     - aws s3api put-object --bucket $CI_COMMIT_BRANCH-facto --key temp
#   environment: $CI_COMMIT_BRANCH